### ISSUE TITLE
Server will exit with timeout error when putting computer in sleep mode

### ISSUE THREAD

**Issue by allan-simon** [allan-simon/py-imap-to-http#1]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/service/__main__.py", line 111, in <module>
    IMAP_PASSWORD,
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/service/__main__.py", line 73, in idle_loop
    yield from asyncio.wait_for(idle, 30)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

**Comment by allan-simon** [comment]
need to see what's cleanest solution to let the service try to reconnect in that case.

**Comment by Ramblurr** [comment]
Running into this too. 

One solution might be to just exit, in which case if running in docker with the restart flag set, docker will just restart the container.

If we don't want to exit, then using a retry lib like `[tenacity](https://github.com/jd/tenacity)` to easily perform an exponential backoff would work well.
